### ISSUE TITLE
Running './install-kubeflow.sh deploy' , got message that the stack was successfully created but I didn't see any resources created

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/kubeflow-on-eks-using-codepipeline#2]
After digging, the reason was because my AWS CLI profile. CLI profile used default profile with region=us-west-2. In fact I could see CloudFormation and pipeline created in Oregon region but the pipeline failed because there was no codecommit repository. You can either change your default profile region or export environment variable as below

export AWS_DEFAULT_REGION=us-east-1
export AWS_REGION=us-east-1

Re-running deploy script will then create resources in proper region

**Comment by kashygau** [comment]
Updated Deployment process to incorporate latest version of EKS and kubeflow.
